/*
 * Vacuum Cleaner Cloud Service
 * This is a sample Vacuum Cleaner Cloud Service server. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vacuumcleaner@vacuumcleaner.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Programma;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for StoreApi
 */
@Ignore
public class StoreApiTest {

    private final StoreApi api = new StoreApi();

    /**
     * Delete purchase programma by ID
     *
     * For valid response try integer IDs with positive integer value.\\ \\ Negative or non-integer values will generate API errors
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteprogrammaTest() throws Exception {
        Long programmaId = null;
        api.deleteprogramma(programmaId);

        // TODO: test validations
    }
    /**
     * Returns vacuumcleaner inventories by status
     *
     * Returns a map of status codes to quantities
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInventoryTest() throws Exception {
        Map<String, Integer> response = api.getInventory();

        // TODO: test validations
    }
    /**
     * Find purchase programma by ID
     *
     * For valid response try integer IDs with value &gt;&#x3D; 1 and &lt;&#x3D; 10.\\ \\ Other values will generated exceptions
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getprogrammaByIdTest() throws Exception {
        Long programmaId = null;
        Programma response = api.getprogrammaById(programmaId);

        // TODO: test validations
    }
    /**
     * Place an programma for a vacuumcleaner
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void placeprogrammaTest() throws Exception {
        Programma body = null;
        Programma response = api.placeprogramma(body);

        // TODO: test validations
    }
}
